name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World!"
  context-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print github info
        run: echo "${{toJson(github)}}"
