name: Fourth workflow
on:
  pull_request:
    types: opened
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '.github/workflows/*'
jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue
        run: echo "${{toJson(github)}}"
